config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'

  root 'inicio#index'
  # Rutas de recurso Ejemplo
  resources :ejemplos 
  
  # Rutas para Tipos
  resources :tipos

  # Rutas para Elementos y Comentarios
  resources :elementos do
    resources :comentarios
  end
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
	belongs_to :elemento
end

app/models/ejemplo.rb
class Ejemplo < ActiveRecord::Base
end

app/models/elemento.rb
class Elemento < ActiveRecord::Base
  belongs_to :tipo
	has_many :comentarios
  mount_uploader :imagen, ImagenUploader
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
	has_many :elementos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  class ComentariosController < ApplicationController
  def index
    @comentarios = Comentario.all
  end

  def show
  end

  def new
    @comentario = Comentario.new
  end

  def edit
  end

  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario creado exitosamente' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario borrado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    def comentario_params
      params.require(:comentario).permit(:nombre)
    end
end

end

app/controllers/ejemplos_controller.rb
class EjemplosController < ApplicationController
  before_action :set_ejemplo, only: [:show, :edit, :update, :destroy]

  # GET /ejemplos
  # GET /ejemplos.json
  def index
    @ejemplos = Ejemplo.all
  end

  # GET /ejemplos/1
  # GET /ejemplos/1.json
  def show
  end

  # GET /ejemplos/new
  def new
    @ejemplo = Ejemplo.new
  end

  # GET /ejemplos/1/edit
  def edit
  end

  # POST /ejemplos
  # POST /ejemplos.json
  def create
    @ejemplo = Ejemplo.new(ejemplo_params)

    respond_to do |format|
      if @ejemplo.save
        format.html { redirect_to @ejemplo, notice: 'Ejemplo was successfully created.' }
        format.json { render :show, status: :created, location: @ejemplo }
      else
        format.html { render :new }
        format.json { render json: @ejemplo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ejemplos/1
  # PATCH/PUT /ejemplos/1.json
  def update
    respond_to do |format|
      if @ejemplo.update(ejemplo_params)
        format.html { redirect_to @ejemplo, notice: 'Ejemplo was successfully updated.' }
        format.json { render :show, status: :ok, location: @ejemplo }
      else
        format.html { render :edit }
        format.json { render json: @ejemplo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ejemplos/1
  # DELETE /ejemplos/1.json
  def destroy
    @ejemplo.destroy
    respond_to do |format|
      format.html { redirect_to ejemplos_url, notice: 'Ejemplo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ejemplo
      @ejemplo = Ejemplo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ejemplo_params
      params.require(:ejemplo).permit(:nombre, :numero)
    end
end

app/controllers/elementos_controller.rb
class ElementosController < ApplicationController
  before_action :set_elemento, only: [:show, :edit, :update, :destroy]

  def index
    @elementos = Elemento.all
  end

  def show
  end

  def new
    @elemento = Elemento.new
  end

  def edit
  end

  def create
    @elemento = Elemento.new(elemento_params)

    respond_to do |format|
      if @elemento.save
        format.html { redirect_to @elemento, notice: 'Elemento creado exitosamente' }
        format.json { render :show, status: :created, location: @elemento }
      else
        format.html { render :new }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @elemento.update(elemento_params)
        format.html { redirect_to @elemento, notice: 'Elemento actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @elemento }
      else
        format.html { render :edit }
        format.json { render json: @elemento.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @elemento.destroy
    respond_to do |format|
      format.html { redirect_to elementos_url, notice: 'Elemento borrado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_elemento
      @elemento = Elemento.find(params[:id])
    end

    def elemento_params
      params.require(:elemento).permit(:nombre, :descripcion, :imagen, :foto, :precio, :caracteristicas, :tipo_id, :created_at, :updated_at)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    if params[:tipo] 
      @elementos = Elemento.where(tipo_id: params[:tipo]) 
    else
      @elementos = Elemento.all
    end
    @tipos = Tipo.all
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  def index
    @tipos = Tipo.all
  end

  def show
  end

  def new
    @tipo = Tipo.new
  end

  def edit
  end

  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo creado exitosamente' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo borrado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    def tipo_params
      params.require(:tipo).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/ejemplos_helper.rb
module EjemplosHelper
end

app/helpers/elementos_helper.rb
module ElementosHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_field :contenido %>
  </div>
  <div class="field">
    <%= f.label :email_autor %><br>
    <%= f.text_field :email_autor %>
  </div>  
  <div class="field">
    <%= f.label :nombre_autor %><br>
    <%= f.text_field :nombre_autor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/_listado.html.erb
<h3> Comentarios para <%= @elemento.nombre %> <small>   Mostrando <%= @elemento.comentarios.count %> comentarios </small></h3>

<br>
<% @elemento.comentarios.each do |c| %>
<div class="well">
  <div class="media">
    <a class="pull-left"><img src="/img/no_img.png" class= "media-object" height="70px"></a>
    <div class="media-body">
      <h4 class="media-heading"><%= c.nombre_autor%> <small><%= c.email_autor %></small></h4>
      <p><%= c.contenido %></p>
      <p class="text-info text-right"> enviado el <%= c.updated_at.to_formatted_s(:short) %></p>
    </div>
  </div>
<% end %>
</div>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Contenido</th>
      <th>Email autor</th>
      <th>Nombre autor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.nombre %></td>
        <td><%= comentario.contenido %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comentario.nombre %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/ejemplos/_form.html.erb
<%= form_for(@ejemplo) do |f| %>
  <% if @ejemplo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ejemplo.errors.count, "error") %> prohibited this ejemplo from being saved:</h2>

      <ul>
      <% @ejemplo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ejemplos/edit.html.erb
<h1>Editing ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Show', @ejemplo %> |
<%= link_to 'Back', ejemplos_path %>

app/views/ejemplos/index.html.erb
<h1>Listing ejemplos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ejemplos.each do |ejemplo| %>
      <tr>
        <td><%= ejemplo.nombre %></td>
        <td><%= ejemplo.numero %></td>
        <td><%= link_to 'Show', ejemplo %></td>
        <td><%= link_to 'Edit', edit_ejemplo_path(ejemplo) %></td>
        <td><%= link_to 'Destroy', ejemplo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ejemplo', new_ejemplo_path %>

app/views/ejemplos/new.html.erb
<h1>New ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Back', ejemplos_path %>

app/views/ejemplos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ejemplo.nombre %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @ejemplo.numero %>
</p>

<%= link_to 'Edit', edit_ejemplo_path(@ejemplo) %> |
<%= link_to 'Back', ejemplos_path %>

app/views/elementos/_form.html.erb
<div class="col-md-6">
<%= form_for @elemento, :html => {:multipart => true, :role => "form"} do |f| %>
  <% if @elemento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@elemento.errors.count, "error") %> impidieron que el elemento se guarde:</h2>

      <ul>
      <% @elemento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre ,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion  ,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :imagen %><br>
    <%= image_tag(@elemento.imagen_url) if @elemento.imagen? %>
    <%= f.file_field :imagen %>
    <%= f.hidden_field :imagen_cache %>
  </div>
  <div class="form-group">
    <%= f.label :precio %><br>
    <%= f.number_field :precio  ,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :caracteristicas %><br>
    <%= f.text_area :caracteristicas  ,class: "form-control" , rows:"3"%>
  </div>
  <div class="form-group">
    <%= f.label :tipo %><br>
    <%= f.collection_select :tipo_id, Tipo.all, :id, :nombre, :selected => @elemento.tipo_id  ,class: "form-control" %>
  </div>
    <%= f.submit "Guardar" ,class: "btn btn-primary" %>
<% end %>
</div>

app/views/elementos/_listado.html.erb
<% @elementos.each do |elemento| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag elemento.imagen_url.to_s %>
      <div class="caption">
        <h3> <%= elemento.nombre %> </h3>
        <p><%= elemento.descripcion %></p>
        <p>
          <%= link_to 'Ver', elemento_path(elemento), class: "btn btn-primary" %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/elementos/edit.html.erb
<h1>Editing elemento</h1>

<%= render 'form' %>

<%= link_to 'Show', @elemento %> |
<%= link_to 'Back', elementos_path %>

app/views/elementos/index.html.erb
<h1>Listing elementos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elementos.each do |elemento| %>
      <tr>
        <td><%= elemento.nombre %></td>
        <td><%= elemento.descripcion %></td>
        <td><%= link_to 'Show', elemento %></td>
        <td><%= link_to 'Edit', edit_elemento_path(elemento) %></td>
        <td><%= link_to 'Destroy', elemento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New elemento', new_elemento_path %>

app/views/elementos/new.html.erb
<h1>New elemento</h1>

<%= render 'form' %>

<%= link_to 'Back', elementos_path %>

app/views/elementos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <%= image_tag @elemento.imagen_url.to_s , class: "img-responsive"%>
  </div>
  <div class="col-md-8">
    <h1><%= @elemento.nombre %><small class="label label-success pull-right">
      <%= number_to_currency(@elemento.precio, :delimiter => '.', :unit => "Gs. ", :precision => 0) %></small></h1>
    <p><%= @elemento.descripcion %></p>
    <p><strong>Características</strong>
      <%= @elemento.caracteristicas %>
    </p>
    <p><strong>Categoría: </strong> <%= link_to @elemento.tipo.nombre, @elemento.tipo %></p>
    <div class="btn-group">
      <%= link_to 'Editar', edit_elemento_path(@elemento), class: "btn btn-primary" %>
    </div>
    <div class="btn-group">
      <%= link_to 'Atrás', elementos_path, class: "btn btn-default" %>
    </div>
  </div>
</div>
<hr>
<%= render 'comentarios/listado' %>

app/views/inicio/index.html.erb
<div class="row">
  <div class="col-md-2">
    <%= render 'tipos/listado' %>
  </div>
  <div class="col-md-10">
    <%= render 'elementos/listado' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProyectoRailsCTN</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Inicio</a>
    </div>
    <%= link_to "Agregar elemento", new_elemento_path, class: "btn btn-success navbar-btn pull-right" %>
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/_listado.html.erb
<ul class="list-group">
  <% @tipos.each do |tipo| %>
    <%= link_to({:controller => :inicio, :action => :index, :tipo => tipo.id}) do%>
    <li class="list-group-item">
      <span class="badge"><%= tipo.elementos.count %></span>
      <%= tipo.nombre%>
    </li>
    <% end %>
  <% end %>
</ul> 

app/views/tipos/edit.html.erb
<h1>Editing tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<h1>Listing tipos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.nombre %></td>
        <td><%= link_to 'Show', tipo %></td>
        <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New ejemplo</h1>

<%= render 'form' %>

<%= link_to 'Back', ejemplos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @tipo.nombre %>
</p>


<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>